#!/usr/bin/env ruby

require_relative "./lib/rgit-init"
require_relative "./lib/rgit-add"
require_relative "./lib/rgit-commit"

command, *args = ARGV

if command.nil?
  $stderr.puts "Usage: rgit <command> [<args>]"
  exit 1
end

case command
  when "init" then RGit::init(*args)
  when "add" then RGit::add(*args)
  when "commit" then RGit::commit(*args)
  else 
    puts "No such command"
    exit 1
end

